### ISSUE TITLE
Vanilla 2.2 bug

### ISSUE THREAD

**Issue by clementbirkle** [swook/Mediator#9]
Hello,

This module doesn't work with Vanilla 2.2
Uncaught TypeError: $(...).live is not a function

Apparently it would rather use .on () ?

**Comment by swook** [comment]
Hey I'm very sorry I never got back to this. I forgot about the issue amidst many other issues in life.

Could you please try the latest release out to confirm this has been fixed?

https://vanillaforums.org/addon/mediator-plugin-0.2.18

Thanks a lot.

**Comment by angeljs6** [comment]
The pastebin doesn't seem to work :(

**Comment by swook** [comment]
Hi @angeljs6 , this is a different issue and I cannot address it here. Please feel free to send me an e-mail (see @swook) with an example page where you have the issue.
